"""Data stack — RDS PostgreSQL and the application secrets.

The DB password is generated by RDS into a Secrets Manager secret (never in
code). The app-secrets secret is created structure-only: `JWT_SECRET` is
generated, the external keys (Anthropic, Google OAuth, Fernet token key) are
empty placeholders the owner fills in out-of-band with `put-secret-value`.
"""

import json

from aws_cdk import RemovalPolicy, Stack
from aws_cdk import aws_ec2 as ec2
from aws_cdk import aws_rds as rds
from aws_cdk import aws_secretsmanager as secretsmanager
from constructs import Construct

DB_NAME = "track_my_subs"


class DataStack(Stack):
    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        *,
        vpc: ec2.IVpc,
        **kwargs,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)

        self.database = rds.DatabaseInstance(
            self,
            "Postgres",
            # .of() (not the VER_* enum) so we can pin an exact minor that's
            # actually offered in ap-southeast-2 (16.4 was retired).
            engine=rds.DatabaseInstanceEngine.postgres(
                version=rds.PostgresEngineVersion.of("16.9", "16")
            ),
            instance_type=ec2.InstanceType.of(
                ec2.InstanceClass.BURSTABLE4_GRAVITON, ec2.InstanceSize.MICRO
            ),
            vpc=vpc,
            vpc_subnets=ec2.SubnetSelection(subnet_type=ec2.SubnetType.PRIVATE_WITH_EGRESS),
            credentials=rds.Credentials.from_generated_secret("dbadmin"),
            database_name=DB_NAME,
            allocated_storage=20,
            max_allocated_storage=50,
            multi_az=False,
            storage_encrypted=True,
            publicly_accessible=False,
            # Early-stage: allow easy teardown. Tighten before holding real data.
            deletion_protection=False,
            delete_automated_backups=True,
            removal_policy=RemovalPolicy.DESTROY,
        )
        # from_generated_secret always populates .secret.
        self.db_secret = self.database.secret
        assert self.db_secret is not None

        # App config/secrets. JWT_SECRET is generated; the rest are placeholders
        # the owner fills in (real values never live in the repo).
        self.app_secret = secretsmanager.Secret(
            self,
            "AppSecret",
            secret_name="track-my-subs/app",
            description="track_my_subs application secrets (fill placeholders out-of-band)",
            generate_secret_string=secretsmanager.SecretStringGenerator(
                secret_string_template=json.dumps(
                    {
                        "ANTHROPIC_API_KEY": "",
                        "TOKEN_ENCRYPTION_KEY": "",
                        "GOOGLE_OAUTH_CLIENT_ID": "",
                        "GOOGLE_OAUTH_CLIENT_SECRET": "",
                        "FRONTEND_ORIGIN": "",
                    }
                ),
                generate_string_key="JWT_SECRET",
                exclude_punctuation=True,
                password_length=48,
            ),
        )
